# Generated by Django 2.2.10 on 2020-12-07 02:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewListingVariable2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('TACInd', models.CharField(blank=True, max_length=255)),
                ('fileNoInd', models.CharField(blank=True, max_length=255)),
                ('modelInd', models.CharField(blank=True, max_length=255)),
                ('brandInd', models.CharField(blank=True, max_length=255)),
                ('marketingNameInd', models.CharField(blank=True, max_length=255)),
                ('typeOfProductInd', models.CharField(blank=True, max_length=255)),
                ('activeIndicator', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['TACInd'],
            },
        ),
    ]
