# Generated by Django 2.2.10 on 2020-12-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewListingVariable2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewlistingvariable2',
            name='approveDateInd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='viewlistingvariable2',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='viewlistingvariable2',
            name='expiryDateInd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='viewlistingvariable2',
            name='nric',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AddField(
            model_name='viewlistingvariable2',
            name='submissionDateInd',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
