# Generated by Django 2.2.10 on 2021-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQCategory', '0002_auto_20210203_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqcategory',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
