# Generated by Django 2.2.10 on 2021-02-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQCategory', '0003_faqcategory_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='content',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
