# Generated by Django 2.2.10 on 2021-03-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQCategory', '0004_auto_20210208_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
