# Generated by Django 2.2.10 on 2021-03-16 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQCategory', '0005_auto_20210315_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcategory',
            options={'ordering': ['created_date']},
        ),
    ]
