# Generated by Django 2.2 on 2021-07-17 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FAQCategory', '0006_auto_20210316_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFAQCategory',
            fields=[
                ('categoryId', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('active', models.BooleanField()),
                ('category', models.CharField(blank=True, max_length=255)),
                ('createdBy', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('modified_date', models.DateTimeField(blank=True, editable=False)),
                ('content', models.CharField(blank=True, max_length=10000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical faq category',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
