# Generated by Django 2.2 on 2021-08-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQCategory', '0007_historicalfaqcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='content',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='historicalfaqcategory',
            name='content',
            field=models.CharField(blank=True, max_length=1000000),
        ),
    ]
