# Generated by Django 2.2.10 on 2021-03-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailTemplate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
