# Generated by Django 2.2.10 on 2021-03-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailTemplate', '0003_auto_20210316_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='template_code',
            field=models.CharField(blank=True, choices=[('1', 'Success'), ('2', 'Fail'), ('0', 'Not Choose')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_content',
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
