# Generated by Django 2.2.10 on 2020-12-16 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productregistration',
            options={'ordering': ['modified_date']},
        ),
    ]
