# Generated by Django 2.2.10 on 2020-12-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0002_auto_20201216_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productregistration',
            old_name='ProductRegistrationId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='productregistration',
            old_name='IMEI',
            new_name='approveDate',
        ),
        migrations.RenameField(
            model_name='productregistration',
            old_name='ProductRegNo',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productregistration',
            old_name='regType',
            new_name='consigneeName',
        ),
        migrations.RenameField(
            model_name='productregistration',
            old_name='serialNo',
            new_name='expiryDate',
        ),
        migrations.RemoveField(
            model_name='productregistration',
            name='user_type',
        ),
        migrations.AddField(
            model_name='productregistration',
            name='fileNo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productregistration',
            name='imeiNo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productregistration',
            name='modelDescription',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productregistration',
            name='modelId',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productregistration',
            name='productCategory',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productregistration',
            name='submissionDate',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
