# Generated by Django 2.2.10 on 2021-02-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0003_auto_20201216_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregistration',
            name='serialNo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
