# Generated by Django 2.2.10 on 2021-03-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0004_productregistration_serialno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productregistration',
            options={'ordering': ['created_date']},
        ),
        migrations.RenameField(
            model_name='productregistration',
            old_name='approveDate',
            new_name='CA_owner',
        ),
        migrations.RenameField(
            model_name='productregistration',
            old_name='consigneeName',
            new_name='IMEI',
        ),
        migrations.RenameField(
            model_name='productregistration',
            old_name='expiryDate',
            new_name='ProductRegistrationNo',
        ),
        migrations.RenameField(
            model_name='productregistration',
            old_name='category',
            new_name='RegType',
        ),
        migrations.RenameField(
            model_name='productregistration',
            old_name='imeiNo',
            new_name='SerialNo',
        ),
        migrations.RemoveField(
            model_name='productregistration',
            name='modelDescription',
        ),
        migrations.RemoveField(
            model_name='productregistration',
            name='modelId',
        ),
        migrations.RemoveField(
            model_name='productregistration',
            name='productCategory',
        ),
        migrations.RemoveField(
            model_name='productregistration',
            name='serialNo',
        ),
        migrations.RemoveField(
            model_name='productregistration',
            name='submissionDate',
        ),
        migrations.AlterField(
            model_name='productregistration',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
