# Generated by Django 2.2.10 on 2021-03-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0005_auto_20210330_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productregistration',
            name='fileNo',
        ),
    ]
