# Generated by Django 2.2.10 on 2021-03-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0006_remove_productregistration_fileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregistration',
            name='FileNo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
