# Generated by Django 2.2.10 on 2021-04-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0008_productregistration_slp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productregistration',
            name='SLP',
        ),
    ]
