# Generated by Django 2.2.10 on 2021-04-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SLP', '0001_initial'),
        ('ProductRegistration', '0009_remove_productregistration_slp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregistration',
            name='SLP_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SLP', to='SLP.SLP'),
        ),
    ]
