# Generated by Django 2.2.10 on 2021-04-09 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0010_productregistration_slp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productregistration',
            name='SLP_id',
        ),
    ]
