# Generated by Django 2.2 on 2021-10-15 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0011_remove_productregistration_slp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_count', models.CharField(blank=True, max_length=255)),
                ('current_product', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
