# Generated by Django 2.2 on 2021-10-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0012_serialdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialdata',
            name='imei_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serialdata',
            name='serial_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
