# Generated by Django 2.2 on 2021-10-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0013_auto_20211015_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serialdata',
            old_name='current_product',
            new_name='total_product',
        ),
    ]
