# Generated by Django 2.2 on 2021-10-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0014_auto_20211016_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialdata',
            name='total_product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
