# Generated by Django 2.2 on 2021-10-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductRegistration', '0015_auto_20211016_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialdata',
            name='total_product_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
