apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: client-appname-webapp
  name: client-appname-webapp
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      app: client-appname-webapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-appname-webapp
    spec:
      containers:
      - image: username/client-appname-webapp:1.0.0
        imagePullPolicy: Always   
        name: client-appname-webapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30