apiVersion: v1
kind: Service
metadata:
  name: client-appname-webapp
  labels:
    service: client-appname-webapp
  name: client-appname-webapp
spec:
  selector:
    app: client-appname-webapp
  ports:
  - port: 80
    targetPort: 80