# Generated by Django 2.2.10 on 2020-12-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQTitle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqtitle',
            name='active',
            field=models.BooleanField(),
        ),
    ]
