# Generated by Django 2.2.10 on 2020-12-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQTitle', '0002_auto_20201221_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqtitle',
            name='created_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='faqtitle',
            name='modified_date',
            field=models.DateTimeField(),
        ),
    ]
