# Generated by Django 2.2.10 on 2020-12-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQTitle', '0003_auto_20201229_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqtitle',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
