# Generated by Django 2.2.10 on 2020-12-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQTitle', '0004_auto_20201229_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqtitle',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
