# Generated by Django 2.2.10 on 2021-03-15 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQTitle', '0007_auto_20201229_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqtitle',
            options={'ordering': ['created_date']},
        ),
    ]
