# Generated by Django 2.2.10 on 2021-03-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailNoti', '0002_auto_20210315_0212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnoti',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='emailnoti',
            name='emailCode',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
