# Generated by Django 2.2 on 2021-08-01 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailNoti', '0004_historicalemailnoti'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnoti',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_CustomUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalemailnoti',
            name='name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
