# Generated by Django 2.2.10 on 2021-03-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variableConfigure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableconfigure',
            name='variable_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
