apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcmc-database-api-deployment
  labels:
    app: mcmc-database-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcmc-database-api
  template:
    metadata:
      labels:
        app: mcmc-database-api
    spec:
      containers:
      - name: mcmc-database-api
        image: syafiqpipe/mcmc-database-api:1.0.7 #boleh tambah version
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
          - secretRef:
              name: mcmc-database-api-secret