# Generated by Django 2.2.10 on 2021-03-25 02:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productCertification',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('FileNo', models.CharField(blank=True, max_length=255)),
                ('TAC', models.CharField(blank=True, max_length=255)),
                ('TypeOfProduct', models.CharField(blank=True, max_length=255)),
                ('Model', models.CharField(blank=True, max_length=255)),
                ('Brand', models.CharField(blank=True, max_length=255)),
                ('MarketingName', models.CharField(blank=True, max_length=255)),
                ('ApproveDate', models.CharField(blank=True, max_length=255)),
                ('ExpiryDate', models.CharField(blank=True, max_length=255)),
                ('ProductCategory', models.CharField(blank=True, max_length=255)),
                ('CertholderName', models.CharField(blank=True, max_length=255)),
                ('ROCROB', models.CharField(blank=True, max_length=255)),
                ('CA_owner', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
