# Generated by Django 2.2 on 2021-10-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productCertification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcertification',
            name='Brand',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='productcertification',
            name='MarketingName',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='productcertification',
            name='Model',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='productcertification',
            name='TypeOfProduct',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
