# Generated by Django 2.2.10 on 2021-03-19 02:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certifiedAgency',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ca_name', models.CharField(blank=True, max_length=255)),
                ('createdBy', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('appoint_date', models.CharField(blank=True, max_length=255)),
                ('expiry_date', models.CharField(blank=True, max_length=255)),
                ('pic_name', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField()),
                ('path', models.CharField(blank=True, max_length=255)),
                ('port', models.CharField(blank=True, max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('ca_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
