# Generated by Django 2.2.10 on 2021-03-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifiedAgency', '0003_auto_20210319_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifiedagency',
            name='appoint_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certifiedagency',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
