# Generated by Django 2.2 on 2021-07-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifiedAgency', '0005_apidetails_historicalapidetails_historicalcertifiedagency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifiedagency',
            name='appoint_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certifiedagency',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcertifiedagency',
            name='appoint_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcertifiedagency',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
