# Generated by Django 2.2 on 2021-08-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifiedAgency', '0006_auto_20210727_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifiedagency',
            name='ca_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='historicalcertifiedagency',
            name='ca_id',
            field=models.IntegerField(default=1),
        ),
    ]
