# Generated by Django 2.2 on 2021-08-31 15:51

import certifiedAgency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifiedAgency', '0007_auto_20210830_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifiedagency',
            name='ca_id',
            field=models.IntegerField(default=certifiedAgency.models.certifiedAgency.number, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='historicalcertifiedagency',
            name='ca_id',
            field=models.IntegerField(db_index=True, default=certifiedAgency.models.certifiedAgency.number, verbose_name='Code'),
        ),
    ]
