# Generated by Django 2.2 on 2021-09-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SLP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slp',
            name='ApproveDate',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='slp',
            name='ExpiryDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
