# Generated by Django 2.2.10 on 2020-12-16 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('fileNo', models.CharField(blank=True, max_length=255)),
                ('TAC', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('modelID', models.CharField(blank=True, max_length=255)),
                ('modelDescription', models.CharField(blank=True, max_length=255)),
                ('consigneeName', models.CharField(blank=True, max_length=255)),
                ('submissionDate', models.CharField(blank=True, max_length=255)),
                ('approveDate', models.CharField(blank=True, max_length=255)),
                ('expiryDate', models.CharField(blank=True, max_length=255)),
                ('deviceCategory', models.CharField(blank=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['TAC'],
            },
        ),
    ]
