# Generated by Django 2.2.10 on 2020-12-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasearch',
            name='serialNo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
