# Generated by Django 2.2 on 2021-08-16 06:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userHistory',
            fields=[
                ('historyId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_type', models.CharField(blank=True, max_length=255)),
                ('history_user_id', models.CharField(blank=True, max_length=255)),
                ('history_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['history_date'],
            },
        ),
    ]
