# Generated by Django 2.2 on 2021-08-18 10:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersHistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='history_user_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
    ]
