# Generated by Django 2.2 on 2021-08-22 13:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersHistory', '0002_auto_20210818_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='history_user_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
