# Generated by Django 2.2 on 2021-08-22 14:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersHistory', '0003_auto_20210822_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='history_user_id',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='history_user_id',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
