# Generated by Django 2.2 on 2021-08-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersHistory', '0004_auto_20210822_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhistory',
            old_name='history_user_id',
            new_name='history_user',
        ),
    ]
