# Generated by Django 2.2.10 on 2020-12-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ViewListingVariable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewlistingvariable',
            options={},
        ),
        migrations.RemoveField(
            model_name='viewlistingvariable',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='viewlistingvariable',
            name='marketingNameInd',
        ),
        migrations.RemoveField(
            model_name='viewlistingvariable',
            name='nric',
        ),
        migrations.RemoveField(
            model_name='viewlistingvariable',
            name='typeOfProductInd',
        ),
    ]
