# Generated by Django 2.2.10 on 2020-12-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewListingVariable', '0002_auto_20201208_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewlistingvariable',
            name='ROCROBind',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='viewlistingvariable',
            name='approveDateInd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='viewlistingvariable',
            name='certHolderNameInd',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='viewlistingvariable',
            name='expiryDateInd',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='viewlistingvariable',
            name='marketingNameInd',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='viewlistingvariable',
            name='submissionDateInd',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
